export const APP_ROUTES = {
  LANDING: {
    ROOT: 'landing',
    HOME: 'home',
    ABOUT: 'about',
    CLASSES: 'classes',
    HEALTHY: 'healthy',
    PROFILE: 'profile',
    CHANGE_PASSWORD: 'change-password',
    Meal_Details: 'meal-details/',
    CHANGE_WEIGHT: 'change-weight',
    CHANGE_GOAL: 'change-goal',
    CHANGE_LEVEL: 'change-level',
    Class_Details: 'class-details',
  },
  AUTH: {
    ROOT: 'auth',
    LOGIN: 'login',
    REGISTER: 'register',
    FORGET_PASSWORD: 'forget-password',
    SET_PASSWORD: 'set-password',
    RESET_PASSWORD: 'reset-password',
    PROFILE: 'profile',
  },
};
